dataset: pokec_n
encoder: appnp
lr: 0.005
hidden_dim: 64
pre_epochs: 200
epochs: 60
cf_warm_epochs: 200
cf_exp_epochs: 60
cf_joint_epochs: 30
warm_sensitive_loss: prototype
lambda_zu_con: 0.0
lambda_zs_fair: 0.0
lambda_y: 2.0
lambda_s: 0.1
lambda_ind: 0.5
lambda_orth: 0.5
lambda_reduce: 2.0
lambda_u_suf: 2.0
lambda_sp: 0.01
mask_feature_budget: 0.3
mask_structure_budget: 0.25
lambda_mask_budget: 1.0
force_retrain_disentangler: true
